# Generated by Django 5.2.5 on 2025-09-14 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intensity', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bicept', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('body_water', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('need_cal', models.IntegerField()),
                ('eaten_cal', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Cali',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('series', models.IntegerField()),
                ('rep', models.IntegerField()),
                ('extra', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Max',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='PhisicalActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intensity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.intensity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.type')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.type'),
        ),
    ]
