# Generated by Django 5.2.5 on 2025-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phisicalactivity',
            name='type',
            field=models.TextField(choices=[('Cardio', 'Cardio'), ('Calisthenics', 'Calisthenics')], default='Cardio'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.TextField(choices=[('Cardio', 'Cardio'), ('Calisthenics', 'Calisthenics')], default='Cardio'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
