# Generated by Django 5.2.5 on 2025-09-16 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_phisicalactivity_type_alter_exercise_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Max',
            new_name='Maximals',
        ),
    ]
