# Generated by Django 5.2.5 on 2025-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_rename_max_maximals'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='fat_mass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='body',
            name='metabolic_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='body',
            name='visceral_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
