# Generated by Django 5.2.5 on 2025-09-22 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_body_fat_mass_body_metabolic_age_body_visceral_fat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='phisicalactivity',
            name='intensity',
            field=models.TextField(choices=[('1', 'Absent'), ('2', 'Minimal'), ('3', 'Decent'), ('4', 'Medium'), ('5', 'Hight'), ('6', 'Extreme')], default='1'),
        ),
        migrations.AddField(
            model_name='cali',
            name='rest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('quality', models.TextField(choices=[('1', 'None'), ('2', 'Minimal'), ('3', 'Decent'), ('4', 'Medium'), ('5', 'Hight'), ('6', 'Wanderluf')], default='1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Intensity',
        ),
    ]
