# Generated by Django 5.2.5 on 2025-08-28 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='account_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.assetclass'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='account_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.assetclass'),
        ),
        migrations.AddField(
            model_name='investment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='instrument_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.instrument'),
        ),
        migrations.AddField(
            model_name='label',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='label_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.label'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
