# Generated by Django 5.2.5 on 2025-09-02 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_transactions', to='finance.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.TextField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Transfer', 'Transfer')], default='Income'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account'),
        ),
    ]
