# Generated by Django 5.2.5 on 2025-08-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_mail_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='local',
        ),
    ]
